accounts/urls.py
from django.urls import path 
from accounts.views import ProfileView, RegisterView

app_name = 'accounts'


urlpatterns = [
    path('signup/', RegisterView.as_view(), name='signup'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

bookShop/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include('django.contrib.auth.urls')),
    path("accounts/", include("accounts.urls")),
    path("cart/", include("cart.urls")),
    path("orders/", include("orders.urls")),
    path('', include('shop.urls'))
]

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('cart_detail/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='add'),
    path('remove/<int:product_id>/', views.cart_remove, name='remove'),
]

orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    ]

shop/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import (BooksSearchView,
                    HomePageView,
                    CustomersListView,
                    OrdersListView,
                    OrderDetailView,
                    BookDetailView,
                    BooksListView,
                    StarsSearchView,
                    StarsView,)
app_name = 'shop'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('customers', CustomersListView.as_view(), name='customers'),
    path('orders', OrdersListView.as_view(), name='orders'),
    path('orders/<int:pk>', OrderDetailView.as_view(), name='order_detail'),
    path('books', BooksListView.as_view(), name='books'),
    path('books/<int:pk>', BookDetailView.as_view(), name='book_detail'),
    path('books_search', BooksSearchView.as_view(), name='search_books'),
    path('stars', StarsView.as_view(), name='stars'),
    path('stars_search', StarsSearchView.as_view(), name='search_stars'),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range (1, 10)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Book
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Book, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Book, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

templates/cart/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>Document</title>
</head>
<body>
    <nav style="background-color: #f0f0f0; padding: 10px;">
        <a href="{% url 'shop:home' %}" style="margin-right: 20px;">Главная</a>
        <a href="{% url 'shop:books' %}" style="margin-right: 20px;">Поиск</a>
        <a href="{% url 'accounts:profile' %}" style="margin-right: 20px;">Профиль</a>
        <a href="{% url 'cart:cart_detail' %}" style="margin-right: 20px;">Корзина</a>
        <a href="{% url 'shop:orders' %}" style="margin-right: 20px;">Заказы</a>
        <a href="{% url 'shop:stars' %}">Избранное </a>
    </nav>
    {% block content %}
    <div class="cart">
        {% with total_items=cart|length %}
        {% if cart|length > 0 %}
        <h1>Ваша корзина:
            <a href="{% url 'cart:cart_detail' %}">
                Итого количество: {{ total_items }}; сумма - {{ cart.get_total_price }} рублей
            </a>
        </h1>
        {% else %}
        <h1>Корзина пустая.</h1>
        {% endif %}
        {% endwith %}
    </div>
    <table class=""cart>
        <thead>
            <tr>
                <th></th>
                <th>Книга</th>
                <th>Количество</th>
                <th>Цена за штуку</th>
                <th>Сумма</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            {% with product=item.book %}    
            <tr>
                <td><img class="productImage" style="height: 200px" src="
                    {{ product.img.url }}"></td>
                <td>{{ product.title }} - {{ product.author }}</td>
                <td>
                    <form action="{% url 'cart:add' product.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.override }}
                    <input type="number" name="quantity" value="{{ item.quantity }}"
                    min="1" max="10" style="margin-left: 10px; width: 50px">
                    <input type="hidden" name="update" value="true" style="margin-left:
                    10px">
                    <input type="submit" value="Обновить">
                    {% csrf_token %}
                    </form>
                </td>
                <td>{{ product.price }} руб.</td>
                <td>{{ item.total_price }} руб.</td>
                <td>
                    <form action="{% url 'cart:remove' item.book.id%}" method="post">
                    <input type="submit" value="Удалить">
                    {% csrf_token %}
                    </form>
                </td>
            </tr>
            {% endwith %}
            {% endfor %}
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'shop:books' %}" class="button-light">Продолжить покупки</a><br>
        <a href="/">Вернуться на главную</a><br>
        <a href="{% url 'orders:order_create' %}">Оформить заказ</a>
    </p>
    {% endblock %}
</body>
</html>