accounts/urls.py
from django.urls import path 
from accounts.views import ProfileView, RegisterView

app_name = 'accounts'


urlpatterns = [
    path('signup/', RegisterView.as_view(), name='signup'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

bookShop/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include('django.contrib.auth.urls')),
    path("accounts/", include("accounts.urls")),
    path("cart/", include("cart.urls")),
    path("orders/", include("orders.urls")),
    path('', include('shop.urls'))
]

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('cart_detail/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='add'),
    path('remove/<int:product_id>/', views.cart_remove, name='remove'),
]

orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    ]

shop/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import (BooksSearchView,
                    HomePageView,
                    CustomersListView,
                    OrdersListView,
                    OrderDetailView,
                    BookDetailView,
                    BooksListView,
                    StarsSearchView,
                    StarsView,)
app_name = 'shop'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('customers', CustomersListView.as_view(), name='customers'),
    path('orders', OrdersListView.as_view(), name='orders'),
    path('orders/<int:pk>', OrderDetailView.as_view(), name='order_detail'),
    path('books', BooksListView.as_view(), name='books'),
    path('books/<int:pk>', BookDetailView.as_view(), name='book_detail'),
    path('books_search', BooksSearchView.as_view(), name='search_books'),
    path('stars', StarsView.as_view(), name='stars'),
    path('stars_search', StarsSearchView.as_view(), name='search_stars'),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)

class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


########################### MY MODELS ######################################
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.db import models

class CustomUserManager(BaseUserManager):
    """Класс для управления создания пользователе"""
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('Email обязателен')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if not extra_fields.get('is_staff'):
            raise ValueError('Суперпользователь должен иметь is_staff=True')
        if not extra_fields.get('is_superuser'):
            raise ValueError('Суперпользователь должен иметь is_superuser=True')

        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField("Имя", max_length=256)
    last_name = models.CharField("Фамилия", max_length=256)
    phone_number = models.CharField("Номер телефона", max_length=20, default='1')
    date_joined  = models.DateTimeField("Дата создания", auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'phone_number']

    def __str__(self):
        return self.email


class Category(models.Model):
    """Модель категории книги"""
    id = models.AutoField("ID", primary_key=True)
    name = models.CharField("Название категории", max_length=256)

    def __str__(self):
        return f'Категория - {self.name}'


class Book(models.Model):
    """Модель книги"""
    id = models.AutoField("ID", primary_key=True)
    title = models.CharField("Название", max_length=256)
    author = models.CharField("Автор", max_length=256)
    price = models.DecimalField("Цена", max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, verbose_name="Категория",
                                 on_delete=models.SET_NULL, null=True)
    description = models.TextField("Описание")
    publishing = models.CharField("Издательство", max_length=128)

    BUNDING_CHOICES = (
        ('soft', 'Мягкий'),
        ('hard', 'Твердый')
    )

    type_of_bunding = models.CharField("Тип переплета", max_length=64, choices=BUNDING_CHOICES)
    stock_quantity = models.PositiveIntegerField("Количество на складе", default=0)
    img = models.ImageField("Изображение", upload_to='img/')

    def __str__(self):
        return f'Книга {self.title} {self.author} (ID {self.id})'


class Comment(models.Model):
    """Модель комментария"""
    id = models.AutoField("ID", primary_key=True)
    book = models.ForeignKey(Book, verbose_name="Книга", on_delete=models.CASCADE)
    customer = models.ForeignKey(CustomUser, verbose_name="Покупатель", on_delete=models.CASCADE)
    comment_date = models.DateField("Дата комментария", auto_now_add=True)
    comment = models.TextField("Комментарий")

    def __str__(self):
        return f'Комментарий {self.customer} (ID {self.id})'


class Order(models.Model):
    """Модель заказа"""
    id = models.AutoField("ID", primary_key=True)
    created_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    first_name = models.CharField("Имя", max_length=50, blank=False)
    last_name = models.CharField("Фамилия", max_length=50, blank=False)
    country = models.CharField("Страна", max_length=32, blank=False)
    state = models.CharField("Область", max_length=255, blank=False)
    city = models.CharField("Город", max_length=255, blank=False)
    street = models.CharField("Улица", max_length=255, blank=False)
    home = models.CharField("Дом", max_length=10, blank=False)
    order_date = models.DateTimeField("Дата создания заказа", auto_now_add=True)
    updated_at = models.DateTimeField("Дата обновления заказа", auto_now=True)
    total_cost = models.DecimalField("Стоимость заказа", max_digits=10, decimal_places=2)
    order_status = models.BooleanField(default=False)

    PAY_METHOD = (
        ('card', 'Картой при получении'),
        ('money', 'Наличыми при получении')
    )

    payment_method = models.CharField("Способ оплаты", max_length=20, choices=PAY_METHOD)
    is_delivered = models.BooleanField("Доставлен?", default=False)
    address = models.CharField("Адрес доставки", max_length=255)

    def __str__(self):
        return f"Заказ: {self.id} (ID покупателя {self.created_by.id})"
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    id = models.AutoField("ID", primary_key=True)
    customer = models.ForeignKey(CustomUser, verbose_name="Покупатель", on_delete=models.CASCADE)
    book = models.ForeignKey(Book, verbose_name="Книга", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField("Количество", default=1)
    price = models.DecimalField(max_digits=50, decimal_places=2, default=0, blank=True)
    order = models.ForeignKey(Order, related_name='items', verbose_name="Заказ", on_delete=models.SET_NULL, null=True, blank=True) # on_delete=models.SET_NULL означает, что если заказ будет удален, ссылка в элементе корзины станет NULL,

    def __str__(self):
        return f"Товар: {self.book.title}, {self.quantity} штук)"
    
    def get_total_cost(self):
        return self.price * self.quantity


class CartItem(models.Model):
    """Модель товара корзины"""
    id = models.AutoField("ID", primary_key=True)
    customer = models.ForeignKey(CustomUser, verbose_name="Покупатель", on_delete=models.CASCADE)
    book = models.ForeignKey(Book, verbose_name="Книга", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField("Количество", default=1)
    price = models.DecimalField(max_digits=50, decimal_places=2, default=0, blank=True)
    order = models.ForeignKey(Order, verbose_name="Заказ", on_delete=models.SET_NULL, null=True, blank=True) # on_delete=models.SET_NULL означает, что если заказ будет удален, ссылка в элементе корзины станет NULL,

    def __str__(self):

orders/forms.py
from django import forms
from shop.models import Order
class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name',
                  'last_name',
                  'country',
                  'state',
                  'city',
                  'street',
                  'home',
                  'payment_method']

orders/views.py
from django.shortcuts import render
from shop.models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart

def order_create(request):
    cart = Cart(request)

    if request.method == 'POST':
        form = OrderCreateForm(request.POST)

        if form.is_valid():
            order = form.save(commit=False)
            order.created_by = request.user  # Устанавливаем текущего пользователя как заказчика
            customer = request.user
            total_cost = sum(item['price'] * item['quantity'] for item in cart)
            order.total_cost = total_cost
            order.save()  # Сохраняем заказ

            for item in cart:
                OrderItem.objects.create(order=order,
                                         customer=customer,
                                          book=item['book'],
                                          price=item['price'],
                                          quantity=item['quantity'])
            cart.clear()
            return render(request, 'orders/order/created.html', {'order': order})
    else:
        form = OrderCreateForm()

    return render(request, 'orders/order/create.html', {'cart': cart, 'form': form})

templates/book_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Книга</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
<body>
    <nav style="background-color: #f0f0f0; padding: 10px;">
        <a href="{% url 'shop:home' %}" style="margin-right: 20px;">Главная</a>
        <a href="{% url 'shop:books' %}" style="margin-right: 20px;">Поиск</a>
        <a href="{% url 'accounts:profile' %}" style="margin-right: 20px;">Профиль</a>
        <a href="{% url 'cart:cart_detail' %}" style="margin-right: 20px;">Корзина</a>
        <a href="{% url 'shop:orders' %}" style="margin-right: 20px;">Заказы</a>
        <a href="{% url 'shop:stars' %}">Избранное </a>
    </nav>
    <h1 class="book-style">{{ book.title }}</h1>
    <h2 class="book-style" style="background-color: #8dc2ff;">{{ book.author }}</h2>
    <img src="{{ book.img.url }}" alt="{{ book.title }}" height="400px">
    <h3 class="book-style" style="background-color: #8dc2ff;">Цена: {{ book.price }}</h3>
    <form action="{% url 'cart:add' book.id %}" method="post">
        {% csrf_token %}
        {{ cart_product_form.quantity }}
        <button type="submit">Добавить в корзину</button>
    </form>
</body>
</html>

templates/books.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Книги</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
<body>
    <nav style="background-color: #f0f0f0; padding: 10px;">
        <a href="{% url 'shop:home' %}" style="margin-right: 20px;">Главная</a>
        <a href="{% url 'shop:books' %}" style="margin-right: 20px;">Поиск</a>
        <a href="{% url 'accounts:profile' %}" style="margin-right: 20px;">Профиль</a>
        <a href="{% url 'cart:cart_detail' %}" style="margin-right: 20px;">Корзина</a>
        <a href="{% url 'shop:orders' %}" style="margin-right: 20px;">Заказы</a>
        <a href="{% url 'shop:stars' %}">Избранное </a>
    </nav>
    <form action="{% url 'shop:search_books' %}" method="GET"> 
        <input name="q" type="text" placeholder="Введите название книги или автора..."> 
    </form> 
    <h1 class="book-style">Книги</h1>
    <table>
        <tr>
            <th>     </th>
            <th class="book-style">Книга</th>
            <th class="book-style">Автор</th>
            <th class="book-style">Стоимость</th>
        </tr>
        {% for book in list_of_all_books %}
        <tr>
            <td class="book-style"><img src="{{ book.img.url }}" alt="{{ book.id }}" height="200px"></td>
            <td class="book-style">
                <a href="{% url 'shop:book_detail' book.id %}">{{book.title}}</a>
            </td>
            <td class="book-style">{{ book.author }}</td>
            <td class="book-style">{{ book.price }}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

templates/create.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
    <nav style="background-color: #f0f0f0; padding: 10px;">
        <a href="{% url 'shop:home' %}" style="margin-right: 20px;">Главная</a>
        <a href="{% url 'shop:books' %}" style="margin-right: 20px;">Поиск</a>
        <a href="{% url 'accounts:profile' %}" style="margin-right: 20px;">Профиль</a>
        <a href="{% url 'cart:cart_detail' %}" style="margin-right: 20px;">Корзина</a>
        <a href="{% url 'shop:orders' %}" style="margin-right: 20px;">Заказы</a>
        <a href="{% url 'shop:stars' %}">Избранное </a>
    </nav>
    {% block content %}
        <h1>Заказ:</h1>
        <div class="order-info">
        <h3>Ваш заказ</h3>
        <ul>
            {% for item in cart %}
            <li> {{ item.quantity }} шт. x {{ item.product.product_name }} на
                сумму <span> {{ item.total_price }} руб.</span> </li>
                {% endfor %}
        </ul>
        <p>Всего: {{ cart.get_total_price }} руб.</p>
        </div>
                <form method="post" class="order-form">
                {{ form.as_p }}
                <p><input type="submit" value="Заказать"></p>
                {% csrf_token %}
                </form>
                {% endblock %}
                <a href="/">Вернуться на главную</a>
                </body>
                </html>

templates/created.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>thanks to order</h1> 
</body>
</html>

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>читай город 2.0</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav style="background-color: #f0f0f0; padding: 10px;">
        <a href="{% url 'shop:home' %}" style="margin-right: 20px;">Главная</a>
        <a href="{% url 'shop:books' %}" style="margin-right: 20px;">Поиск</a>
        <a href="{% url 'accounts:profile' %}" style="margin-right: 20px;">Профиль</a>
        <a href="{% url 'cart:cart_detail' %}" style="margin-right: 20px;">Корзина</a>
        <a href="{% url 'shop:orders' %}" style="margin-right: 20px;">Заказы</a>
        <a href="{% url 'shop:stars' %}">Избранное </a>
    </nav>
    <h1>читай город 2.0</h1>
    {% if user.is_authenticated %} 
        <h1>Привет, {{ user.first_name }} {{ user.last_name}}!</h1> 
    {% else %} 
        <p>Вы не вошли на сайт</p> 
        <a href="{% url 'login' %}">Войти</a> 
    {% endif %}  
    <img src="{% static 'img/home.jpg' %}" alt="Django">
</body>
<script src="{% static 'js/script.js' %}"></script>
</html>

templates/orders.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Заказы пользователя</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
<body class="book-style">
    <nav style="background-color: #f0f0f0; padding: 10px;">
        <a href="{% url 'shop:home' %}" style="margin-right: 20px;">Главная</a>
        <a href="{% url 'shop:books' %}" style="margin-right: 20px;">Поиск</a>
        <a href="{% url 'accounts:profile' %}" style="margin-right: 20px;">Профиль</a>
        <a href="{% url 'cart:cart_detail' %}" style="margin-right: 20px;">Корзина</a>
        <a href="{% url 'shop:orders' %}" style="margin-right: 20px;">Заказы</a>
        <a href="{% url 'shop:stars' %}">Избранное </a>
    </nav>
    <h1>Список всех заказов:</h1>
    <table>
        <tr>
            <th>Номер заказа</th>
            <th>Заказ создан</th>
            <th>Имя получателя</th>
            <th>Статус заказа</th>
            <th>Сумма заказа</th>
            <th>Дата создания заказа</th>
        </tr>
        {% for order in list_of_all_orders %}
        <tr>
            <td>
                <a href="{% url 'shop:order_detail' order.id %}">{{order.id}}</a>
            </td>
            <td>{{ order.created_by.first_name }} {{ order.created_by.last_name }}</td>
            <td>{{ order.first_name }} {{ order.last_name }}</td>
            <td>{{ order.order_status }}</td>
            <td>{{ order.total_cost }}</td>
            <td>{{ order.order_date|date:"d-m-Y"}}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

templates/search_books.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Книги</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
<body>
    <nav style="background-color: #f0f0f0; padding: 10px;">
        <a href="{% url 'shop:home' %}" style="margin-right: 20px;">Главная</a>
        <a href="{% url 'shop:books' %}" style="margin-right: 20px;">Поиск</a>
        <a href="{% url 'accounts:profile' %}" style="margin-right: 20px;">Профиль</a>
        <a href="{% url 'cart:cart_detail' %}" style="margin-right: 20px;">Корзина</a>
        <a href="{% url 'shop:orders' %}" style="margin-right: 20px;">Заказы</a>
        <a href="{% url 'shop:stars' %}">Избранное </a>
    </nav>
    <h1 class="book-style">Найденые книги:</h1>
    {% if search_query %}
    <h2>Вы искали: "{{ search_query }}"</h2>
    {% endif %}

    {% if list_of_all_books %}
    <table>
        <tr>
            <th>     </th>
            <th class="book-style">Книга</th>
            <th class="book-style">Автор</th>
            <th class="book-style">Стоимость</th>
            <th></th>
        </tr>
        {% for book in list_of_all_books %}
        <tr>
            <td class="book-style"><img src="{{ book.img.url }}" alt="{{ book.id }}" height="200px"></td>
            <td class="book-style">
                <a href="{% url 'shop:book_detail' book.id %}">{{book.title}}</a>
            </td>
            <td class="book-style">{{ book.author }}</td>
            <td class="book-style">{{ book.price }}</td>
            <td>
                <form action="{% url 'cart:add' book.id %}" method="post">
                    {% csrf_token %}
                    {{ cart_product_form.quantity }}
                    <button type="submit">Добавить в корзину</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <h2>Упс, ничего не найдено...</h2>
    {% endif %}
</body>
</html>

templates/search_stars.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Книги</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
<body>
    <nav style="background-color: #f0f0f0; padding: 10px;">
        <a href="{% url 'shop:home' %}" style="margin-right: 20px;">Главная</a>
        <a href="{% url 'shop:books' %}" style="margin-right: 20px;">Поиск</a>
        <a href="{% url 'accounts:profile' %}" style="margin-right: 20px;">Профиль</a>
        <a href="{% url 'cart:cart_detail' %}" style="margin-right: 20px;">Корзина</a>
        <a href="{% url 'shop:orders' %}" style="margin-right: 20px;">Заказы</a>
        <a href="{% url 'shop:stars' %}">Избранное </a>
    </nav>
    <h1 class="book-style">Найденые книги:</h1>
    {% if search_query %}
    <h2>Вы искали: "{{ search_query }}"</h2>
    {% endif %}

    {% if stars %}
    <table>
        <tr>
            <th>     </th>
            <th class="book-style">Книга</th>
            <th class="book-style">Автор</th>
            <th class="book-style">Стоимость</th>
        </tr>
        {% for star in stars %}
        <tr>
            <td class="book-style"><img src="{{ star.book.img.url }}" alt="{{ star.book.id }}" height="200px"></td>
            <td class="book-style">
                <a href="{% url 'shop:book_detail' star.book.id %}">{{star.book.title}}</a>
            </td>
            <td class="book-style">{{ star.book.author }}</td>
            <td class="book-style">{{ star.book.price }}</td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <h2>Упс, ничего не найдено...</h2>
    {% endif %}
</body>
</html>

templates/stars.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Избранное</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
<body>
    <nav style="background-color: #f0f0f0; padding: 10px;">
        <a href="{% url 'shop:home' %}" style="margin-right: 20px;">Главная</a>
        <a href="{% url 'shop:books' %}" style="margin-right: 20px;">Поиск</a>
        <a href="{% url 'accounts:profile' %}" style="margin-right: 20px;">Профиль</a>
        <a href="{% url 'cart:cart_detail' %}" style="margin-right: 20px;">Корзина</a>
        <a href="{% url 'shop:orders' %}" style="margin-right: 20px;">Заказы</a>
        <a href="{% url 'shop:stars' %}">Избранное </a>
    </nav>
    <form action="{% url 'shop:search_stars' %}" method="GET"> 
        <input name="q" type="text" placeholder="Введите название книги или автора..."> 
    </form> 
    <h1 class="book-style">Избранное</h1>
    <table>
        <tr>
            <th>     </th>
            <th class="book-style">Книга</th>
            <th class="book-style">Автор</th>
            <th class="book-style">Стоимость</th>
        </tr>
        {% for star in stars %}
        <tr>
            <td class="book-style"><img src="{{ star.book.img.url }}" alt="{{ star.book.id }}" height="200px"></td>
            <td class="book-style">
                <a href="{% url 'shop:book_detail' star.book.id %}">{{star.book.title}}</a>
            </td>
            <td class="book-style">{{ star.book.author }}</td>
            <td class="book-style">{{ star.book.price }}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>